sitewomen/users/urls.py
from django.urls import path, re_path, register_converter, reverse_lazy
from . import views
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


app_name = 'users'

urlpatterns = [
    
    path('login/', views.LoginUser.as_view(), name="login"), # 'users:login'
    path('logout/', LogoutView.as_view(), name="logout"), # 'users.logout'
    
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    # в базовый класс представления можно передавать атрибуты и extra_context
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    # путь если пароль успешно изменен
    path(
        'password-change/done/', 
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
            ), 
        name='password_change_done',
    ),
    ### Восстановление пароля
    # путь на шаблон отправки емейла для восстановление пароля
    path(
        'password-reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            email_template_name='users/password_reset_email.html',
            success_url=reverse_lazy('users:password_reset_done'),
        ), 
        name='password_reset',
    ),
    # шаблон с сообщение об успешной отправке информации на емейл
    path(
        'password-reset/done/', 
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ), 
        name='password_reset_done',
    ),
    # путь на шаблон непосредственно для восстановление пароля
    path('password-reset/<uidb64>/<token>/', 
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete'),
        ), 
        name='password_reset_confirm',
    ),
    # путь на шаблон если пароль был успешно восстановлен
    path(
        'password-reset/complete/', 
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
            ), 
        name='password_reset_complete'
    ),
    
]

sitewomen/users/templates/users/login.html
<!DOCTYPE html>

{% extends 'base.html' %}


{% block content %}
<h1> Авторизация </h1>

<form method="post">
    <!-- next используется для возвращение в основном чтобы после авторизации вернуться на предыдущую страницу -->
    <input type="hidden" name="next" value="{{ next }}" />
    {% csrf_token %}
    <div class="form-error"> {{ form.non_field_errors }}</div>

    {% for f in form%}

    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label  }}</label> {{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>

    {% endfor %}

    <p><button type="submit">Войти</button></p>

    <p><a href="{% url 'users:password_reset' %}" >Забыли пароль?</a></p>

</form>

<hr>
<p>
<!-- вход черех соц сети -->
<a href="{% url 'social:begin' 'github' %}"><img src="/media/social-auth/github.png" alt="github" width="5%" height="5%"></a>
<a href="{% url 'social:begin' 'vk-oauth2' %}"><img src="/media/social-auth/vk.png" alt="vk" width="5%" height="5%"></a>

</p>

{% endblock content %}
    

sitewomen/users/templates/users/password_change_done.html
{% extends 'base.html' %}


{% block content %}
<h1>Пароль успешно изменен!</h1>

<p><a href="{% url 'users:profile' %}">Вернуться в профиль</a></p>

{% endblock content %}

sitewomen/users/templates/users/password_change_form.html
<!DOCTYPE html>
{% extends 'base.html' %}


{% block content %}

<h1>Изменение пароля</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors}} </div>
        
        {% for f in form %}
        <p><label class="form-label" for="{{f.id_for_label}}">{{f.label}}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }} </div>
        {% endfor %}
        
        <p><button type="submit">Изменить пароль</button></p>
    </form>

{% endblock content %}


    

sitewomen/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}


{% block content %}

<h1>Пароль изменен</h1>

<p>Вы успешно изменили пароль своего аккаунта. Используйте его для <a href="{% url 'users:login' %}">входа в систему</a></p>

{% endblock content %}

sitewomen/users/templates/users/password_reset_confirm.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}

<h1>Новый пароль</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors}} </div>
        
        {% for f in form %}
        <p><label class="form-label" for="{{f.id_for_label}}">{{f.label}}</label> {{ f }} </p>
        <div class="form-error">{{ f.errors }} </div>
        {% endfor %}
        
        <p><button type="submit">Сохранить</button></p>
    </form>

{% endblock content %}

sitewomen/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

sitewomen/users/templates/users/password_reset_email.html
<!-- скопировано из django.contrib.admin.templates.registration -->
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

sitewomen/users/templates/users/password_reset_form.html
{% extends 'base.html' %}


{% block content %}

<h1>Восстановление пароля</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors}} </div>
        
        {% for f in form %}
        <p><label class="form-label" for="{{f.id_for_label}}">{{f.label}}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }} </div>
        {% endfor %}
        
        <p><button type="submit">Сбросить по E-mail</button></p>
    </form>

{% endblock content %}

sitewomen/users/templates/users/profile.html
{% extends 'base.html' %}


{% block content %}
    <h1>Профиль</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if user.photo %}
            <p><img src="{{ user.photo.url }}" width="20%" height="20%">
        {% else %}
            <p><img src="{{ default_image }}" width="20%" height="20%">
        {% endif %}
        
        <div class="form-error">{{ form.non_field_errors}} </div>
        
        {% for f in form %}
        <p><label class="form-label" for="{{f.id_for_label}}">{{f.label}}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }} </div>
        {% endfor %}
        
        <p><button type="submit">Сохранить</button></p>
    </form>

{% if not perms.users.social_auth %}
<hr>
<p><a href="{% url 'users:password_change' %}"> Сменить пароль</a></p>
{% endif %}


{% endblock content %}
    

sitewomen/users/templates/users/register.html
{% extends 'base.html' %}


{% block content %}
<h1>Регистрация</h1>
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" /> 

    <div class="form-error"> {{ form.non_field_errors }}</div>

    {% for f in form%}

    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label  }}</label> {{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>

    {% endfor %}

    <p><button type="submit">Регистрация</button></p>
</form>

{% endblock content %}

sitewomen/users/templates/users/register_done.html
{% extends 'base.html' %}


{% block content %}

<h1>Добро пожаловать!</h1>

<p>Вы успешно зарегистрировались на сайте! Для входа необходимо авторизоваться по 
    <a href="{% url 'users:login' %}">ссылке</a>
</p>
    
{% endblock content %}
    