sitewomen/women/urls.py
from django.urls import path, re_path, register_converter
from . import views
from . import converters

# кеширование
from django.views.decorators.cache import cache_page
# cache_page - декоратор
# пример - path('', cache_page(30)(views.WomenHome.as_view()), name='home')

register_converter(converters.FourDigitYearConverter, 'year4')

urlpatterns = [
    path('', views.WomenHome.as_view(), name='home'), # http://127.0.0.1:8000/
    path('about/', views.about, name='about'), #http://127.0.0.1:8000/about/
    path('addpage/', views.AddPage.as_view(), name="add_page"),
    path('contact/', views.ContactFormView.as_view(), name="contact"),
    path('login/', views.login, name="login"),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name="post"),
    path('category/<slug:cat_slug>/', views.WomenCategory.as_view(), name='category'),
    path('tag/<slug:tag_slug>/', views.TagPostList.as_view(), name='tag'),
    path('edit/<slug:slug>/', views.UpdatePage.as_view(), name='edit_page'),
    path('delete/<slug:slug>/', views.DeletePage.as_view(), name='delete_page'),
]


    # path('cats/<int:cat_id>/', views.categories, name='cats_id'), # http://127.0.0.1:8000/cats/2/
    # path('cats/<slug:cat_slug>/', views.categories_by_slug, name='cats'), # http://127.0.0.1:8000/cats/sdfggd/
    # path("archive/<year4:year>", views.archive, name='archive')  # name - маршрут обращения

# машрут.                      функция представления, имя обращения
# path('tag/<slug:tag_slug>/', views.show_tag_postlist, name=tag)
# машрут связан с отображением тегов

#TagPost
# Возращает url адрес для тега
# def get_absolute_url(self):
#         return reverse("tag", kwargs={"tag_slug": self.slug})

sitewomen/women/models.py
from tabnanny import verbose
from django.contrib.auth import get_user_model
from django.core.validators import MaxLengthValidator, MinLengthValidator
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from unidecode import unidecode

# fixture 
# комманда для сохранения модели в json 
# python -Xutf8 manage.py dumpdata --indent=2 women.Women -o women/fixtures/women_women.json

# комманда сохранения всей бд в json 
# python -Xutf8 manage.py dumpdata --indent=2 --exclude contenttypes --exclude social_django -o db.json

class PublishedManager(models.Manager):
    
    # Менеджер моделей
    def get_queryset(self):
        return super().get_queryset().filter(is_published=Women.Status.PUBLISHED)


# Create your models here.
# ORM
class Women(models.Model):
    class Status(models.IntegerChoices):
        # Перечисление
        # Выбор статуса значения is_published
        DRAFT = 0, 'Черновик'
        PUBLISHED = 1, 'Опубликовано'
        # Women.Status.choices [(0, 'Черновик'), (1, 'Опубликовано')]
        # Women.Status.labels ['Черновик', 'Опубликовано']
        # Women.Status.values [0, 1]
    
    title = models.CharField(
        max_length=255, 
        verbose_name='Заголовок',
    )
    slug = models.SlugField(
        max_length=255, 
        unique=True, 
        db_index=True,
        verbose_name='Slug', 
        validators=[
            MinLengthValidator(5, message='Минимум 5 символов'),
            MaxLengthValidator(100, message='Максимум 100 символов'),
        ],
    )
    # фото 
    photo = models.ImageField(
        upload_to='photos/%Y/%m/%d/',
        default=None,
        blank=True,
        null=True,
        verbose_name='Фото'
    )
    content = models.TextField(
        blank=True, 
        verbose_name='Текст статьи',
    )
    time_create = models.DateTimeField(
        auto_now_add=True, 
        verbose_name='Время создания',
    )
    time_update = models.DateTimeField(
        auto_now=True, 
        verbose_name="Время изменения",
    )
    # choices=tuple(map(lambda x: (bool(x[0]), x[1]) костыль для преобразования из choices 0, 1 в булевое значение
    is_published = models.BooleanField(
        choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)),
        default=Status.PUBLISHED, 
        verbose_name="Статус",
    )
    
    # связь таблицы с таблицей category Many_to_one
    cat = models.ForeignKey(
        'Category', 
        on_delete=models.PROTECT, 
        related_name='posts', 
        verbose_name="Категория",
    ) 
    # In [3]: Category.objects.get(pk=1).posts.all()
    
    # теги постов Many_to_Many
    tags = models.ManyToManyField(
        'TagPost', 
        blank=True, 
        related_name='tags', 
        verbose_name="Теги",
    )
    
    # связь с таблицей husband One_to_One
    husband = models.OneToOneField(
        'Husband',
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True, 
        related_name='wuman', 
        verbose_name="Муж",
    )
    
    # поле автора
    author = models.ForeignKey(
        get_user_model(), 
        on_delete=models.SET_NULL, 
        related_name='posts',
        null=True,
        default=None,
    )
    
    
    #экземпляр менеджера моделей
    published = PublishedManager()
    #нужно переопределить менеджер objects, 
    # так как при создании собственного менеджера objects перестает работать
    objects = models.Manager()
    
    
    def __str__(self):
        return self.title

    # Класс Meta определяет порядок и индексы модели в Python.
    class Meta:
        verbose_name = 'Женщины'
        verbose_name_plural = 'Жещины'
        # Сортировка
        ordering =[
            '-time_create'
        ]
        indexes = [
            models.Index(fields=['-time_create'])
        ]
    
    def get_absolute_url(self):
        #возращает url адрес со слагом
        return reverse("post", kwargs={"post_slug": self.slug})
    
    # def save(self, *args, **kwargs):
    #     # автоматическое создание слага
    #     self.slug = slugify(unidecode(str(self.title)))
    #     super().save(*args, **kwargs)



class Category(models.Model):
    # модель связной таблицы для категорий
    name = models.CharField(
        max_length=100,
        db_index=True, 
        verbose_name='Категория',
    )
    slug = models.SlugField(
        max_length=255, 
        unique=True, 
        db_index=True,
    )
    
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("category", kwargs={'cat_slug': self.slug})


class TagPost(models.Model):
    # таблица с тегами постов
    tag = models.CharField(
        max_length=100, 
        db_index=True,
    )
    slug = models.SlugField(
        max_length=255, 
        unique=True, 
        db_index=True,
    )
    
    def __str__(self):
        return self.tag
    
    def get_absolute_url(self):
        return reverse("tag", kwargs={"tag_slug": self.slug})


class Husband(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField(null=True)
    
    def __str__(self):
        return self.name


class UploadFiles(models.Model):
    # модель для загрузки файлов
    file = models.FileField(upload_to='uploads_model')


# класс Q 
# from django.db.models import Q

# Women.objects.filter(pk__lt=5, cat_id=2) # SQL AND
#  WHERE ("women_women"."cat_id" = 2 AND "women_women"."id" < 5)
# Women.objects.filter(Q(pk__lt=5) | Q(cat_id=2)) # SQL OR
#  WHERE ("women_women"."id" < 5 OR "women_women"."cat_id" = 2)
#  Women.objects.filter(Q(pk__lt=5) & Q(cat_id=2)) # SQL AND
#   WHERE ("women_women"."id" < 5 AND "women_women"."cat_id" = 2)
# Women.objects.filter(~Q(pk__lt=5) & Q(cat_id=2)) # SQL NOT=~
#  WHERE (NOT ("women_women"."id" < 5) AND "women_women"."cat_id" = 2)
# Women.objects.filter(~Q(pk__in=[1, 2, 5]) | Q(cat_id=2), title__contains='ра')
#  WHERE ((NOT ("women_women"."id" IN (1, 2, 5)) OR "women_women"."cat_id" = 2) AND "women_women"."title" LIKE '%ра%' ESCAPE '\')


#Создание файла миграции в women.migrations
# python manage.py makemigrations

# python manage.py shell - консоль джанго, похоже на консоль pycharm

# >>> from women.models import Women
# >>> Women(title='Анджелина Джоли', content='Биография Анджелины Джоли')
# <Women: Women object (None)>
# >>> w1 = _
# >>> w1
# <Women: Women object (None)>
# >>> w1.save()
# >>> w1
# <Women: Women object (1)>
# >>> w1.id
# >>> w1.pk - primary key


# >>> from django.db import connection
# >>> connection.queries
# [{'sql': 'INSERT INTO "women_women" ("title", "content", "time_create", "time_update", "is_published") VALUES (\'Анджелина Джоли\', \'Биография Анджелины Джоли\', \'2024-03-15 07:04:02.770419\', \'2024-03-15 07:04:02.771330\', 1) RETURNING "women_women"."id"', 'time': '0.003'}]
# >>> 

# >>> w2 = Women(title='Энн Хэтэуей', content='Биография Энн Хэтэуей')
# >>> w2.save
# <bound method Model.save of <Women: Women object (None)>>
# >>> w2.save()

# >>> w3 = Women()
# >>> w3.title = 'Джулия Робертся'
# >>> w3.content = 'Биография Джулии Робертс'
# >>> w3.save()


# pip install ipython

# pip install django-extensions

# INSTALLED_APPS = (
# ...
# django_extensions',
# )
# python manage.py shell_plus --print-sql  


# In [3]: Women.objects
# Out[3]: <django.db.models.manager.Manager at 0x104606550>

# In [4]: Women.objects.create(title='Ума Турман', content='Биография Умы Турман')
# Women.objects.create(title='Кира Найтли', content='Биография Киры Найтли')

# In [1]: Women.objects.all()
# Execution time: 0.000889s [Database: default]
# <QuerySet [<Women: Анджелина Джоли>, <Women: Энн Хэтэуей>, <Women: Джулия Робертся>, <Women: Екатерина Гусева>, <Women: Ума Турман>, <Women: Кира Найтли>]>


# In [2]: w = Women.objects.all()[0]
# SELECT "women_women"."id",
#        "women_women"."title",
#        "women_women"."content",
#        "women_women"."time_create",
#        "women_women"."time_update",
#        "women_women"."is_published"
#   FROM "women_women"
#  LIMIT 1

# Execution time: 0.000347s [Database: default]

# In [3]: w
# Out[3]: <Women: Анджелина Джоли>

# In [4]: w.title
# Out[4]: 'Анджелина Джоли'

# In [5]: w.content
# Out[5]: 'Биография Анджелины Джоли'

# In [6]: w.pk
# Out[6]: 1

# In [7]: w = Women.objects.all()[:3]
# SQL запрос не добавляется, только после взаимодействий с экземпляром w
# In [8]: w
# Out[8]: SELECT "women_women"."id",
#        "women_women"."title",
#        "women_women"."content",
#        "women_women"."time_create",
#        "women_women"."time_update",
#        "women_women"."is_published"
#   FROM "women_women"
#  LIMIT 3

# Execution time: 0.000309s [Database: default]
# <QuerySet [<Women: Анджелина Джоли>, <Women: Энн Хэтэуей>, <Women: Джулия Робертся>]>

# In [9]: 

# In [9]: ws = Women.objects.all()

# In [10]: for w in ws:
#     ...:     print(w)
#     ...: 
# SELECT "women_women"."id",
#        "women_women"."title",
#        "women_women"."content",
#        "women_women"."time_create",
#        "women_women"."time_update",
#        "women_women"."is_published"
#   FROM "women_women"

# Execution time: 0.002037s [Database: default]
# Анджелина Джоли
# Энн Хэтэуей
# Джулия Робертся
# Екатерина Гусева
# Ума Турман
# Кира Найтли

# Execution time: 0.000155s [Database: default]
# <QuerySet [<Women: Энн Хэтэуей>]>


# Сравение

# In [12]: Women.objects.filter(pk__gt=2)
# Out[12]: SELECT "women_women"."id",
#        "women_women"."title",
#        "women_women"."content",
#        "women_women"."time_create",
#        "women_women"."time_update",
#        "women_women"."is_published"
#   FROM "women_women"
#  WHERE "women_women"."id" > 2
#  LIMIT 21

# Execution time: 0.000122s [Database: default]
# <QuerySet [<Women: Джулия Робертся>, <Women: Екатерина Гусева>, <Women: Ума Турман>, <Women: Кира Найтли>]>


# Включает ли строка LIKE

sitewomen/women/templates/women/about.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}

{% for item in page_obj %}
    <p>{{ item.pk}}: {{item}}</p>
{% endfor %}

<nav>
    <ul>
        
        {% for p in page_obj.paginator.page_range %}
        <li>
            <a href="?page={{ p }}"> {{ p }}</a>
        </li>
        {% endfor %}
            
    </ul>
</nav>

{% endblock %}

sitewomen/women/templates/women/addpage.html
<!DOCTYPE html>
{% extends 'base.html' %}

{%block content%}
<h1>{{title}}</h1>
<!-- enctype="multipart/form-data" обязательно для передачи файлов -->
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- form - экземпляр класса AddPostForm передается из views.addpage (функция предстваления) -->
    <!-- или form по умолчанию, если передается из класса представления -->
    <!-- Автоматическое заполнение форм -->
    <!-- {{ form.as_p }} -->

    <!-- Отображение ошибок которые не связаны с полем ввода -->
    <div class="form-error"> {{ form.non_field_errors }}</div>

    {% for f in form%}

    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label  }}</label> {{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>

    {% endfor %}

    <p><button type="submit">Отправить</button></p>
</form>


{% endblock %}

sitewomen/women/templates/women/contact.html
{% extends 'base.html' %}



{% block content %}
<h1>{{title}}</h1>

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-error"> {{ form.non_field_errors }}</div>

    {% for f in form%}

    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label  }}</label> {{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>

    {% endfor %}

    <p><button type="submit">Отправить</button></p>
</form>
    
{% endblock content %}
    

sitewomen/women/templates/women/delete.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <p> Вы действительно хотите удалить "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
    
{% endblock content %}
    

sitewomen/women/templates/women/index.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}

<ul class="list-articles">

	{% for p in posts %}

	<li><div class="article-panel">
		<p class="first">Категория: {{p.cat.name}} | автор: {{ p.author.username|default:"Неизвестен" }}</p>
		<p class="last">Дата: {{p.time_update|date:"d-m-Y H:i:s"}}</p>

	</div>
{% if p.photo %}
		<p><img src="{{p.photo.url}}" class="img-article-left thumb"></p>
{% endif %}

		<h2>{{p.title}}</h2>

	{% autoescape off%}
	{{p.content|linebreaks|truncatewords:40}}
	{% endautoescape%}
	
			<div class="clear"></div>
			<p class="link-read-post"><a href="{{ p.get_absolute_url }}">Читать пост</a></p>
			</li>
	{% endfor %}

</ul>

{% endblock %}

<!-- Пагинация страницы -->
{% block navigation %}

{% if page_obj.has_other_pages %}
<nav class="list-pages">
    <ul>	
		<!-- ссылка на предыдущую страницу -->
		{% if page_obj.has_previous  %}
			<li class="page-num">
				<a href="?page={{ page_obj.previous_page_number }}"> &lt; </a>
			</li>
		{% endif %}

        {% for p in paginator.page_range %}
		
		{% if page_obj.number == p %}
		<li class="page-num page-num-selected"> {{ p }} </li>
		<!-- Ограничение кнопок страниц -->
		{% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
		
        <li class="page-num">
            <a href="?page={{ p }}"> {{ p }}</a>
        </li>
		{% endif %}
        {% endfor %}

		<!-- ссылка на следующую страницу -->
		{% if page_obj.has_next  %}
			<li class="page-num">
				<a href="?page={{ page_obj.next_page_number }}"> &gt; </a>
			</li>
		{% endif %}
    </ul>
</nav>
{% endif %}
{% endblock navigation %}
	

sitewomen/women/templates/women/list_categories.html
<!DOCTYPE html>
<!-- cat - экземпляр Category -->
{%for cat in cats %}
    {% if cat.id == cat_selected %}
        <li class="selected">{{cat.name}}</li>
    {% else %}
    <!-- get_absolute_url метод экземпляра класса Cat -->
        <li><a href="{{cat.get_absolute_url}}">{{cat.name}}</a></li>
    {% endif%}
{% endfor%}

sitewomen/women/templates/women/list_tags.html
<!DOCTYPE html>
<!-- шаблонный тег tags из women_tags.py -->
<!-- tags экземпляр класса TagPost -->
    <p>Теги:</p>
    <ul class="tags-list">
        {% for t in tags %}
        <!-- get_absolute_url метод экземпляра класса TagPost -->
        <!-- t.get_absolute_url возращает ссылку, t.tag - название тега -->
        <li><a href="{{t.get_absolute_url}}">{{t.tag}}</a></li>

        {%endfor%}
    </ul>

sitewomen/women/templates/women/post.html
<!DOCTYPE html>

{%extends 'base.html'%}

{% block breadcrumbs %}
<!-- django автоматически передает коллекцию perms - разрешения, которыми обладает текущий пользователь (permission) -->
<!-- {{ perms }} -->

{% if perms.women.change_women %}
<p><a href="{% url 'edit_page' post.slug %}">Редактировать</a></p>
{% endif %}
    
<!-- Теги -->
<!-- post.tags.all - ORM команда (SQL) -->
{% with post.tags.all as tags %}

{% if tags %}
<ul class="tags-list">
    <li>Теги:</li>
    {% for t in tags %}
    <!-- get_absolute_url метод экземпляра класса TagPost -->
    <!-- t.get_absolute_url возращает ссылку, t.tag - название тега -->
    <li><a href="{{t.get_absolute_url}}">{{t.tag}}</a></li>
    {% endfor%}
</ul>
{% endif %}
{% endwith %}
{% endblock %}


{%block content%}

<h1>{{post.title}}</h1>

{%if post.photo%}
<p><img class="img-article-left" src="{{post.photo.url}}"></p>
{%endif%}

{{post.content|linebreaks}}
{%endblock%}