sitewomen/sitewomen/urls.py
from django.contrib import admin
from django.urls import path, include
from sitewomen import settings
from women.sitemaps import CategorySitemap, PostSitemap
from women.views import page_not_found
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap

from django.views.decorators.cache import cache_page

# можно передавать любой ключ
sitemaps = {
    'posts': PostSitemap,
    'cats': CategorySitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('women.urls')), # ссылается на файл women.urls.py
    path('users/', include('users.urls', namespace='users')), # 'users:login', 'users.logout', namespace - пространство имен
    path("__debug__/", include("debug_toolbar.urls")),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path('sitemap.xml', cache_page(860000)(sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]   


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = page_not_found

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Известные женщины мира"


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitewomen/users/urls.py
from django.urls import path, re_path, register_converter, reverse_lazy
from . import views
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


app_name = 'users'

urlpatterns = [
    
    path('login/', views.LoginUser.as_view(), name="login"), # 'users:login'
    path('logout/', LogoutView.as_view(), name="logout"), # 'users.logout'
    
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    # в базовый класс представления можно передавать атрибуты и extra_context
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    # путь если пароль успешно изменен
    path(
        'password-change/done/', 
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
            ), 
        name='password_change_done',
    ),
    ### Восстановление пароля
    # путь на шаблон отправки емейла для восстановление пароля
    path(
        'password-reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            email_template_name='users/password_reset_email.html',
            success_url=reverse_lazy('users:password_reset_done'),
        ), 
        name='password_reset',
    ),
    # шаблон с сообщение об успешной отправке информации на емейл
    path(
        'password-reset/done/', 
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ), 
        name='password_reset_done',
    ),
    # путь на шаблон непосредственно для восстановление пароля
    path('password-reset/<uidb64>/<token>/', 
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete'),
        ), 
        name='password_reset_confirm',
    ),
    # путь на шаблон если пароль был успешно восстановлен
    path(
        'password-reset/complete/', 
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
            ), 
        name='password_reset_complete'
    ),
    
]

sitewomen/templates/base.html
<!DOCTYPE html>
<!-- загрузка статики (файлы) -->
{% load static %}
<!-- загрузка пользовательский тегов -->
{% load women_tags %}
<!-- загрузка кеширования -->
<!-- {% load cache %} -->


<html>
<head>
	<title>{{title}}</title>
	<!-- Включение стилей -->
	<link type="text/css" href="{% static 'women/css/styles.css' %}" rel="stylesheet" />
	<!-- Метаданне -->
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'women/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

<table class="table-page" border="0" cellpadding="0" cellspacing="0">
<tr><td valign="top">

{% block mainmenu %}

		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="{% url 'home' %}"><div class="logo"></div></a></li>


{% for m in mainmenu %}
	<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
{% endfor %}

{% if user.is_authenticated %}
	<li class="last"> <a href="{% url 'users:profile' %}"> {{ user.username }} </a> | <a href="{% url 'users:logout' %}">Выйти</a></li>
{% else %}
	<li class="last"><a href="{% url 'users:login' %}">Войти</a> | <a href="{% url 'users:register' %}"> Регистрация </a></li>
{%endif%}
			</ul>
			<div class="clear"></div>
		</div>

{% endblock mainmenu %}


<table class="table-content" border="0" cellpadding="0" cellspacing="0">
<tr>

	<!-- {% cache 30 sidebar%} -->
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
		<!-- cat_selected шаблонный тег из templatetags.women_tags.py -->
		{% if cat_selected == 0 %}
		<li class="selected">Все категории</li>
		{%else%}
		<li><a href="{% url 'home'%}">Все категории</a></li>
		{%endif%}
		<!-- Включающий пользовательский тег -->
		{% show_categories cat_selected %}
		
		<li class="share">
		<p>Наш канал</p>
		<a class="share-yt" href="https://www.youtube.com/channel/UClJzWfGWuGJL2t-3dYKcHTA/playlists" target="_blank" rel="nofollow"></a>
		</li>
		<!-- вызов функции show_all_tags из templatetags.women_tags.py-->
		<li>{% show_all_tags %}</li>

	</ul>
</td>
<!-- Конец Sidebar'а -->
	<!-- {% endcache %} -->

<td valign="top" class="content">
	
	<!-- Хлебне крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->

{% block navigation %}

{% endblock navigation %}
	


</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign="top">
	<div id="footer">
		<p>&copy; 2023 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажнх, строго запрещено.</p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страниц-->
</body>
</html>